#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory

#------------------------------------------------------------------------------

wclean src/errorEstimators
wclean src/dynamicMesh
wclean src/dynamicFvMesh
wclean src/Accessories

wclean applications/utilities/updateMesh
wclean applications/solvers/combustion/reactingDyMFoam
# -----------------------------------------------------------------------------
