name: OF2212
defaults:
  run:
    shell: bash -o pipefail -i {0}
on:
  push:
    branches:
      - v2212
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Tmate debugging session'
        required: false
        default: false

jobs:
  build:
    runs-on: ubuntu-22.04

    container:
      image: ghcr.io/foamscience/jammy-openfoam:v2212
      options: --user openfoam
      env:
        CATCH_TIMEOUT: 120

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          detached: true

      - name: Compile and Test
        run: |
          source /usr/lib/openfoam/openfoam2212/etc/bashrc
          mkdir -p $FOAM_USER_LIBBIN
          ./Allwmake
          git clone https://github.com/FoamScience/foamUT $FOAM_FOAMUT
          sed -i 's/mpirun/mpirun --oversubscribe/g' $FOAM_FOAMUT/Alltest
          ln -s "$PWD"/tests/adaptiveFvMeshTests "$FOAM_FOAMUT/tests/adaptiveFvMeshTests"
          rm -rf "$FOAM_FOAMUT/cases"
          cp -r tests/testCases "$FOAM_FOAMUT/cases"
          cd $FOAM_FOAMUT || exit 1
          rm -rf tests/exampleTests
          ./Alltest "$@"
          if [ -f $FOAM_FOAMUT/tests/adaptiveFvMeshTests/log.wmake ]; then cat $FOAM_FOAMUT/tests/adaptiveFvMeshTests/log.wmake; fi 
